[package]
name = "ex"
version = "0.1.0"
edition = "2021"

[workspace]
# This ensures the package is not part of the parent workspace

[dependencies]
tos-alloc = { path = "../.." }
tako-sdk = { path = "../../../tako/sdk" }

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
lto = true
